### ISSUE TITLE
[FE] 타이어 커스텀 페이지 구현 - 패턴 선택 

### ISSUE THREAD

**Issue by jinlee1703** [endless-horses/oot-web#16]
## Description

사용자가 타이어의 패턴을 선택할 수 있는 페이지 구현

## Task

- [x] 패턴 디자인 선택 페이지 라우팅
- [x] 커스텀 항목 아이템 컴포넌트 구현
- [x] 패턴 디자인 선택 페이지 구현
- [x] 커스텀 항목 선택 프로그레스바 컴포넌트 구현
- [x] 선택된 커스텀 항목 이미지 컴포넌트 구현
- [x] 커스텀 항목 데이터 컴포넌트 구현
- [x] 커스텀 항목 리스트 컴포넌트 구현
