### ISSUE TITLE
[FE] 타이어 커스텀 페이지 구현 - 측면 디자인 선택

### ISSUE THREAD

**Issue by jinlee1703** [endless-horses/oot-web#23]
## Description

사용자가 타이어의 측면 디자인을 선택할 수 있는 페이지 구현

## Task

- [x] color 전역 상태 구현
- [x] font 전역 상태 구현
- [x] 측면 디자인 선택 페이지 라우팅
- [x] 측면 디자인 페이지 구현
