### ISSUE TITLE
[FE] 타이어 커스텀 페이지 구현 - 액세서리 선택

### ISSUE THREAD

**Issue by jinlee1703** [endless-horses/oot-web#25]
## Description

사용자가 타이어의 액세서리를 선택할 수 있는 페이지 구현

## Task

- [x] accessory 전역 상태 구현
- [x] 액세서리 선택 페이지 구현
- [x] 액세서리 페이지 구현
