### ISSUE TITLE
[FE] 결과물 조회 페이지 구현

### ISSUE THREAD

**Issue by jinlee1703** [endless-horses/oot-web#27]
## Description

사용자가 만든 타이어의 결과물을 확인할 수 있는 페이지 구현

## Task

- [ ]  결과물 조회 페이지 구현
- [ ]  결과물 만들기 API 연동
- [ ]  결과물 조회 API 연동
