### ISSUE TITLE
[FE] 타이어 미리보기 컴포넌트 구현

### ISSUE THREAD

**Issue by jinlee1703** [endless-horses/oot-web#28]
## Description

클라이언트를 위한 타이어 커스텀 상태 미리보기 제공을 위한 3D 미리보기 기능 제공

## Task

- [x] Three.js 설치
- [x] 타이어 랜더링 구현
- [x] 타이어 패턴 구현
- [ ] 타이어 휠 모양 구현
- [ ] 타이어 측면 디자인 구현
- [ ] 타이어 악세서리 구현
