### ISSUE TITLE
[FE] 메인 페이지 구현

### ISSUE THREAD

**Issue by jinlee1703** [endless-horses/oot-web#4]
## Description

서비스 메인 페이지 구현

## Task

- [x] Styled-Components 설치
- [x] Logo 컴포넌트 구현
- [x] Header 컴포넌트 구현
- [x] Main 페이지 구현
